ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

default_platform(:ios)

platform :ios do
  lane :release_testflight do |options|
    setup_ci
    api_key = app_store_connect_api_key(
      key_id: ENV["APPLE_KEY_ID"],
      issuer_id: ENV["APPLE_ISSUER_ID"],
      key_content: ENV["APPLE_KEY_CONTENT"],            
      duration: 1200,            
      in_house: false,
    )
    match(
      readonly: false,
      type: "appstore",
      app_identifier: ENV["MATCH_IDENTIFIERS"],
      git_url: "https://github.com/WalletConnect/match-swift.git",
      git_basic_authorization: options[:token],
      api_key: api_key,
      include_all_certificates: true,
      force_for_new_devices: true,
      force_for_new_certificates: true
    )
    number = latest_testflight_build_number(
      app_identifier: ENV["APP_IDENTIFIER"],
      api_key: api_key
    )
    increment_build_number(
      build_number: number + 1,
      xcodeproj: "Sample/Example.xcodeproj"
    )
    gym(
      configuration: "Release",
      project: "Sample/Example.xcodeproj",
      scheme: ENV["SCHEME"],
      export_method: "app-store",
      xcargs: "PROJECT_ID='#{options[:project_id]}'"
    )
    upload_to_testflight(
      apple_id: ENV["APPLE_ID"],
      app_identifier: ENV["APP_IDENTIFIER"],
      changelog: "Web3Modal sample app weekly build 🚀",
      skip_waiting_for_build_processing: true
    )
    clean_build_artifacts()
  end
end